version: "2"

services:
  api:
    image: meteo.api
    #build: ../src/Meteo.Api
    links:
      - sql
    ports:
      - '5000:5000'

  sql:
    image: microsoft/mssql-server-linux
    ports:
      - '1433:1433'
    environment:
      - 'ACCEPT_EULA=Y'
      - 'SA_PASSWORD=abcd1234!'
    volumes:
      - ./sql:/var/opt/mssql